#include "pomp_lib.h"

struct ompregdescr omp_rd_19 = {
  "parallel", "", 0, "sudoku-omp.c", 90, 90, 148, 148
};

#define POMP_DLIST_00019 shared(omp_rd_19,omp_rd_20,omp_rd_21,omp_rd_22,omp_rd_23)

struct ompregdescr omp_rd_20 = {
  "for", "", 0, "sudoku-omp.c", 103, 103, 119, 119
};

struct ompregdescr omp_rd_21 = {
  "critical", "", 0, "sudoku-omp.c", 111, 111, 116, 116
};

struct ompregdescr omp_rd_22 = {
  "for", "", 0, "sudoku-omp.c", 121, 121, 142, 142
};

struct ompregdescr omp_rd_23 = {
  "critical", "", 0, "sudoku-omp.c", 133, 133, 139, 139
};

struct ompregdescr omp_rd_24 = {
  "critical", "", 0, "sudoku-omp.c", 165, 165, 168, 168
};

struct ompregdescr omp_rd_25 = {
  "critical", "", 0, "sudoku-omp.c", 189, 189, 192, 192
};

struct ompregdescr omp_rd_26 = {
  "critical", "", 0, "sudoku-omp.c", 250, 250, 253, 253
};

struct ompregdescr omp_rd_27 = {
  "critical", "", 0, "sudoku-omp.c", 302, 302, 305, 305
};

